### ISSUE TITLE
Separate HTML tags from classes/ids

### ISSUE THREAD

**Issue by orbiteleven** [devongovett/atom-jade#1]
The TextMate and SublimeText jade packages have a different color for HTML tags vs CSS classes and ID's. That'd be nice to have.

**Comment by juanpasolano** [comment]
I have tried many different color schemes but i still have the same color for Ids, classes and content, and the comment blocks don't get grayed out
What am i doing wrong?

![screen shot 2015-07-04 at 11 07 10](https://cloud.githubusercontent.com/assets/1621720/8508615/e609318a-223c-11e5-8684-b9e31a1b0235.png)

You say this has been closed for long but ....
