### ISSUE TITLE
Comments not highlighted when preceded by an odd number of blank lines...

### ISSUE THREAD

**Issue by peterwmwong** [devongovett/atom-jade#16]
![jade-comments](https://cloud.githubusercontent.com/assets/284734/4262126/362e5acc-3b8f-11e4-8ca6-3124696d32ed.gif)

I dunno if this helps...

![screen shot 2014-09-13 at 4 41 31 pm](https://cloud.githubusercontent.com/assets/284734/4262130/508a9642-3b8f-11e4-8533-5c55184f29a1.png)

![screen shot 2014-09-13 at 4 38 41 pm](https://cloud.githubusercontent.com/assets/284734/4262132/5a6a0be8-3b8f-11e4-8050-f6a5d1749922.png)

**Comment by tylerFowler** [comment]
Plus one for this. I also find that multiple styles of comments that this issue, both `//` and `//-`

**Comment by irrationalistic** [comment]
So I did a little exploring (also related to #26, and maybe a few others), and I think this is all related to a specific rule in the given grammar:
https://github.com/devongovett/atom-jade/blob/master/grammars/jade.cson#L258

This line targets all other general tags and adds the proper classes to them, but for some reason it conflicts with the styles that are already being supplied by the previous instruction. If you comment that entire section out, it will actually fix the problem (while disabling common tag detection). I don't think this is an issue with this package though, and may reveal a bigger issue in atom itself! Any thoughts on what to do about this? Something we should bring up with the atom head honchos?

**Comment by irrationalistic** [comment]
In my explorations I've discovered the first-mate atom module that is responsible for handling the actual parsing and application of grammar files. I posted an issue there to see if they had any thoughts and just put together a pull request that demonstrates the failing cases for odd-line comments. Just more FYI on progress!

https://github.com/atom/first-mate/issues/38

**Comment by renanveroneze** [comment]
News?

**Comment by irrationalistic** [comment]
There is a pull request on first-mate that shows an error in tests for this example, but no word yet. Probably need to bump the thread listed (https://github.com/atom/first-mate/issues/38) to get some visibility?
