### ISSUE TITLE
Syntax appears incorrectly in comments

### ISSUE THREAD

**Issue by dbeff** [devongovett/atom-jade#17]
I use Atom with spacegrey theme and in my case the comments appears like this:

![image](https://cloud.githubusercontent.com/assets/5122156/4345946/4aea3f40-40e8-11e4-9efc-61fff01b840a.png)

**Comment by mrmlnc** [comment]
@devongovett, @LinusU, please, close this issue.

Not reproduced in Atom `1.11.0-beta5` & VS Code `1.5.0`.

![image](https://cloud.githubusercontent.com/assets/7034281/18348476/2bdc5e1c-75d4-11e6-96bb-54551c09475f.png)

**Comment by LinusU** [comment]
Confirmed working, thanks!
