### ISSUE TITLE
"include some.css" throws off formatting

### ISSUE THREAD

**Issue by bbar** [devongovett/atom-jade#19]
Here's an example:
![screen shot 2014-11-13 at 3 14 45 pm](https://cloud.githubusercontent.com/assets/599210/5038659/26e6a1da-6b48-11e4-9e42-60f617489729.png)

**Comment by mrmlnc** [comment]
@devongovett, @LinusU, please, close this issue.

Will be fixed #72.

![image](https://cloud.githubusercontent.com/assets/7034281/18348545/9f8b4404-75d4-11e6-9d11-ae0e37c31987.png)

**Comment by LinusU** [comment]
Fixed by #72
