### ISSUE TITLE
Whitespace auto-trim not working

### ISSUE THREAD

**Issue by samu** [devongovett/atom-jade#21]
The [whitespace package](https://github.com/atom/whitespace) automatically trims trailing whitespaces after save. This isn't working for jade files. I'm not sure if this is a problem with this package or with atom itself.

**Comment by szexigexi** [comment]
this is a problem for me as well, i think this package should respect the whitespace settings.

@devongovett could you reopen this issue?

**Comment by szimek** [comment]
Any updates on this issue?

**Comment by devongovett** [comment]
I no longer use Atom and don't have time to maintain this package. If someone wants to take it on, I will gladly transfer ownership of this repo to you.

**Comment by matthojo** [comment]
@devongovett Have you found a new maintainer for this project?

**Comment by LinusU** [comment]
@matthojo I've been added as a maintainer for the project and will be quick to respond to questions and merge pull requests. I can't add you as a maintainer thought, only @devongovett can.

Re. the issue: The whitespace package has deliberately chosen to ignore jade files and I don't think that we should overrule there decision. See atom/whitespace#46 and atom/whitespace#52.
