### ISSUE TITLE
Syntax colouring off after 'else'

### ISSUE THREAD

**Issue by macpham** [devongovett/atom-jade#22]
![image](https://cloud.githubusercontent.com/assets/1777724/5706022/81b096b6-9a4b-11e4-82d8-80576a2a7bd1.png)

After an `else` statement, it seems the syntax colouring doesn't work unless there is a an empty line after.

**Comment by CavemanNinja** [comment]
+1 came here to post this.

**Comment by AMalininHere** [comment]
+1

**Comment by dogancelik** [comment]
:+1:

**Comment by tikiking1** [comment]
+1

**Comment by tusbar** [comment]
:+1:

**Comment by nathanbuchar** [comment]
:+1:

**Comment by ilikebits** [comment]
:+1:

**Comment by Krajsnick** [comment]
Also came here to post this. I hope someone into code grammars could have a PR for this!
