### ISSUE TITLE
Copy and Pasting breaks formating 

### ISSUE THREAD

**Issue by Silom** [devongovett/atom-jade#24]
If I copy and past e.g. this into a jade file:

```
div
div
div
```

becomes this:

```
div
  div
    div
```

**Comment by e-jigsaw** [comment]
@Silom It is atom feature. If you do not like this, you can turn off this feature in Settings pane

![2015-01-31 17 51 45](https://cloud.githubusercontent.com/assets/557961/5987516/f29b7456-a971-11e4-94b5-3c196db3568e.png)

Turn off `Auto Indent On Paste`.

**Comment by Silom** [comment]
@e-jigsaw nice, thanks.
