### ISSUE TITLE
script highlight is breaking

### ISSUE THREAD

**Issue by e-jigsaw** [devongovett/atom-jade#25]
`script` highlight is work when

```jade
some
  script(type='text/javascript').
    var x = 'lol';
```

insert new line before `script`

```jade
some

  script(type='text/javascript')
    var x = 'lol';
```

it is not highlight.

`test/test.jade`:

![2015-01-31 17 33 23](https://cloud.githubusercontent.com/assets/557961/5987492/517433b2-a96f-11e4-92b3-99e40b932a30.png)

![2015-01-31 17 37 48](https://cloud.githubusercontent.com/assets/557961/5987497/f59b086c-a96f-11e4-8da2-65548139a54f.png)

Thanks

**Comment by mrmlnc** [comment]
@devongovett, @LinusU, please, close this issue.

Not reproduced in Atom `1.11.0-beta5`.

![2016-09-08_15-03-50](https://cloud.githubusercontent.com/assets/7034281/18348690/832df7ba-75d5-11e6-8be3-c3152045be89.gif)

**Comment by e-jigsaw** [comment]
I decided to use `language-pug`. No longer using this package. Thanks a lot
