### ISSUE TITLE
Inline html breaking coloring?

### ISSUE THREAD

**Issue by dbox** [devongovett/atom-jade#47]
Is this markup error, or has something changed in the new update?
![uvbvc4ujg3ocofvopb6xani1hka_0rhosvce_qgzqcy](https://cloud.githubusercontent.com/assets/296130/7815947/209a7572-0391-11e5-9af4-d312ed106754.png)

//cc @ccampb13

**Comment by juanpasolano** [comment]
I also have experience highlighting errors... I don't know If its this package or the color scheme...
The commenting is 
![screen shot 2015-07-04 at 10 54 17](https://cloud.githubusercontent.com/assets/1621720/8508570/360f4a40-223b-11e5-9ee2-c37b55a58445.png)

And also: what color scheme are you using I cant get my jade to put classes in a different color than content.

**Comment by fpereira1** [comment]
This doesn't seem to be an issue anymore unless there's something related to the rest of the file that I don't have access to.

See screenshot:

![](https://s3.amazonaws.com/f.cl.ly/items/2d0B3V2i292P241Q2i1d/Image%202016-01-30%20at%2011.50.03%20AM.png?v=585d23b8)

**Comment by mrmlnc** [comment]
@devongovett, @LinusU, please, close this issue.

Not reproduced in Atom `1.11.0-beta5` & VS Code `1.5.0`.
