### ISSUE TITLE
Conflict with removeTrailingWhitespace

### ISSUE THREAD

**Issue by FuriouZz** [devongovett/atom-jade#48]
The `removeTrailingWhitespace` is not working when I use your syntax highlighting.

**Comment by LinusU** [comment]
Please use the search field before reporting new issues. This is a duplicate of #21.

> Re. the issue: The whitespace package has deliberately chosen to ignore jade files and I don't think that we should overrule their decision. See atom/whitespace#46 and atom/whitespace#52.
