### ISSUE TITLE
Comment not being stylized

### ISSUE THREAD

**Issue by smaili** [devongovett/atom-jade#52]
I noticed that when a comment is one or more lines after, it does not get stylized.

**Next line**
![yes](https://cloud.githubusercontent.com/assets/4451986/8578810/cc5e2ade-2565-11e5-9eaa-14a7009b0a8d.png)

**Next next line**
![no](https://cloud.githubusercontent.com/assets/4451986/8578815/d0581168-2565-11e5-9ae5-edfc86ddac40.png)

**Comment by eddiemonge** [comment]
same as #16 ?

**Comment by smaili** [comment]
Yes they seem to be the same.  Closing this issue in favor of #16.
