### ISSUE TITLE
"Blocks in tag" not recognised if preceded by empty line

### ISSUE THREAD

**Issue by ilikebits** [devongovett/atom-jade#59]
If an empty line precedes a tag marked with a plain text block, the leading words in the plain text block are recognised as tags instead. This may be a generalisation of #58.

See screenshots.

![screenshot from 2015-12-27 16 32 16](https://cloud.githubusercontent.com/assets/2092654/12012731/a51ea4a6-acb7-11e5-91e9-f2043ce54841.png)
![screenshot from 2015-12-27 16 32 20](https://cloud.githubusercontent.com/assets/2092654/12012730/a51e281e-acb7-11e5-9fb5-881a72ac4c4c.png)

**Comment by isiahmeadows** [comment]
I have the same problem. Granted, every Jade highlighter for Atom I've found seems shoddy at best.

**Comment by mrmlnc** [comment]
@devongovett or @LinusU, please, close this issue.

Not reproduced in Atom `1.11.0-beta5` & VS Code `1.5.0`.

![2016-09-08_14-44-34](https://cloud.githubusercontent.com/assets/7034281/18348220/cecc1e66-75d2-11e6-8194-95a8bf64b259.gif)

**Comment by LinusU** [comment]
Confirmed working, thanks!
