### ISSUE TITLE
Relatively few colors are used to distinguish many parts of this syntax theme.

### ISSUE THREAD

**Issue by ZombieHippie** [devongovett/atom-jade#64]
Atom with built in Atom Dark theme
![image](https://cloud.githubusercontent.com/assets/2925395/13375979/cec0a9ca-dd73-11e5-926a-dc1bf8a6b5f9.png)

Sublime with Monokai variant
![image](https://cloud.githubusercontent.com/assets/2925395/13375982/e0416d38-dd73-11e5-8f61-bba12de7d3d9.png)

As you can see with a *built-in* theme there are very few things that atom-jade is currently distinguishing. It did not bother me when I was using it at first, but when I had to teach someone jade, the lack of syntax highlights made learning very difficult, like inline javascript being the same color as the classes tags, etc.

I will submit several different pull requests that utilize similar styling names as the packaged language-css for atom.

**Comment by LinusU** [comment]
Fixed in 0.7.0
